from __future__ import annotations

import asyncio
import contextlib
import functools
import inspect
import json
import logging
import os
import urllib.parse
import zoneinfo
from collections.abc import AsyncIterator
from datetime import date as _date_cls
from datetime import datetime, time, timezone
from pathlib import Path
from typing import Any, cast

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials

from lilical.backends.base import (
    AuthExpired,
    ConflictError,
    CursorExpired,
    EventChange,
    PermanentError,
    SyncCursor,
    TransientError,
)
from lilical.models.contact import Contact
from lilical.models.event import Attendee, Event, Organizer
from lilical.utils.timezone import local_iana_tz, local_zoneinfo

log = logging.getLogger(__name__)

GOOGLE_BASE = "https://www.googleapis.com/calendar/v3"

# Minimal field mask for events.list — only what _google_event_to_change reads.
_EVENTS_LIST_FIELDS = (
    "nextPageToken,nextSyncToken,"
    "items(id,iCalUID,etag,status,recurringEventId,summary,description,location,"
    "htmlLink,transparency,updated,sequence,recurrence,"
    "start(date,dateTime,timeZone),end(date,dateTime,timeZone),"
    "originalStartTime(date,dateTime,timeZone),"
    "organizer(email,displayName,self),"
    "attendees(email,displayName,self,responseStatus,organizer))"
)

SCOPES = [
    "https://www.googleapis.com/auth/calendar",
    "https://www.googleapis.com/auth/calendar.events",
    # CardDAV gives access to the user's personal address book without any
    # Sensitive-scope warnings or Workspace admin allowlist requirements.
    "https://www.googleapis.com/auth/carddav",
]


def _load_client_config() -> dict[str, object]:
    # 1. Env vars — always win; useful for contributors and CI.
    client_id = os.environ.get("LILICAL_GOOGLE_CLIENT_ID")
    client_secret = os.environ.get("LILICAL_GOOGLE_CLIENT_SECRET")
    if client_id and client_secret:
        return {
            "installed": {
                "client_id": client_id,
                "client_secret": client_secret,
                "redirect_uris": ["http://127.0.0.1"],
                "auth_uri": os.environ.get(
                    "LILICAL_GOOGLE_AUTH_URI",
                    "https://accounts.google.com/o/oauth2/auth",
                ),
                "token_uri": os.environ.get(
                    "LILICAL_GOOGLE_TOKEN_URI",
                    "https://oauth2.googleapis.com/token",
                ),
            }
        }

    # 2. Embedded module — generated by tools/generate_oauth_embedded.py at
    #    build time and frozen into Flatpak/AppImage bundles.
    try:
        from lilical import _oauth_embedded  # type: ignore[import]

        return {
            "installed": {
                "client_id": _oauth_embedded.CLIENT_ID,
                "client_secret": _oauth_embedded.CLIENT_SECRET,
                "redirect_uris": ["http://127.0.0.1"],
                "auth_uri": _oauth_embedded.AUTH_URI,
                "token_uri": _oauth_embedded.TOKEN_URI,
            }
        }
    except ImportError:
        pass

    # 3. oauth_credentials.json at the repo root — picked up in dev when
    #    running via `pixi run run` without env vars set.
    for parent in Path(__file__).resolve().parents:
        candidate = parent / "oauth_credentials.json"
        if candidate.is_file():
            with candidate.open() as f:
                data: dict[str, object] = json.load(f)
            installed = dict(cast(dict[str, object], data.get("installed", {})))
            installed.setdefault("redirect_uris", ["http://127.0.0.1"])
            return {"installed": installed}

    # 4. Placeholder — _validate_client_config will raise a clear error.
    return {"installed": {"client_id": "lilical-oauth", "client_secret": ""}}


CLIENT_CONFIG = _load_client_config()


# Map Google Calendar responseStatus → our normalized vocabulary.
_GOOGLE_RESPONSE_MAP: dict[str, str] = {
    "accepted": "ACCEPTED",
    "tentative": "TENTATIVE",
    "declined": "DECLINED",
    "needsaction": "NEEDS-ACTION",
}


def _people_to_contacts(
    people: list[object], account_id: str, source: str
) -> list[Contact]:
    out: list[Contact] = []
    for p in people:
        if not isinstance(p, dict):
            continue
        name: str | None = None
        names = p.get("names") or []
        if isinstance(names, list) and names:
            n = names[0]
            if isinstance(n, dict):
                name = str(n.get("displayName") or "").strip() or None
        emails = p.get("emailAddresses") or []
        if not isinstance(emails, list):
            continue
        resource_name = str(p.get("resourceName") or "")
        for e in emails:
            if not isinstance(e, dict):
                continue
            addr = str(e.get("value") or "").strip().lower()
            if not addr or "@" not in addr:
                continue
            out.append(
                Contact(
                    email=addr,
                    display_name=name,
                    source=source,
                    account_id=account_id,
                    source_id=resource_name or None,
                )
            )
    return out


class GoogleCursor(SyncCursor):
    _TYPE = "google"

    def __init__(self, sync_token: str | None = None) -> None:
        self.sync_token = sync_token

    def to_json(self) -> dict[str, object]:
        return {"_type": self._TYPE, "sync_token": self.sync_token}

    @classmethod
    def from_json(cls, data: dict[str, object]) -> GoogleCursor:
        if data.get("_type") != cls._TYPE:
            raise ValueError(f"not a google cursor: {data!r}")
        return cls(sync_token=data.get("sync_token"))  # type: ignore[reportArgumentType]


def _status_of(exc: Exception) -> int | None:
    resp = getattr(exc, "response", None)
    if resp is not None:
        status = getattr(resp, "status_code", None)
        if isinstance(status, int):
            return status
    return None


def _classify_one(exc: Exception) -> Exception:
    status = _status_of(exc)
    if status in (401, 403):
        # Note: Google returns 403 for some rate-limit responses too, not just
        # auth failures. This pre-existing mapping is intentional — changing
        # it would require a separate, careful fix.
        return AuthExpired(str(exc))
    if status == 410:
        return CursorExpired()
    if status == 412:
        return ConflictError(str(exc))
    if status is not None and (status == 429 or status >= 500):
        return TransientError(str(exc))
    return PermanentError(str(exc))


def _classify_errors(f):
    if inspect.isasyncgenfunction(f):

        @functools.wraps(f)
        async def wrapper(*args, **kwargs):
            try:
                async for item in f(*args, **kwargs):
                    yield item
            except (
                AuthExpired,
                CursorExpired,
                ConflictError,
                TransientError,
                PermanentError,
            ):
                raise
            except Exception as exc:
                raise _classify_one(exc) from exc

        return wrapper

    @functools.wraps(f)
    async def wrapper_coro(*args, **kwargs):
        try:
            return await f(*args, **kwargs)
        except (
            AuthExpired,
            CursorExpired,
            ConflictError,
            TransientError,
            PermanentError,
        ):
            raise
        except Exception as exc:
            raise _classify_one(exc) from exc

    return wrapper_coro


def _parse_google_dt(
    part: dict[str, object] | None,
) -> tuple[datetime | None, str, bool]:
    """Resolve a Google start/end object to (datetime, tz, all_day).

    Google's start/end is either:
      - {"date": "YYYY-MM-DD"}  → all-day, returned as naive midnight datetime
        so EventStore._ensure_aware_dt treats it as UTC midnight.
      - {"dateTime": "...", "timeZone": "America/Los_Angeles"}  → timed; if the
        parsed dateTime is naive, the timeZone field is applied.
    """
    if not part:
        return None, "UTC", False
    if "date" in part:
        try:
            d = _date_cls.fromisoformat(str(part["date"]))
            local = local_zoneinfo()
            return datetime.combine(d, time.min, tzinfo=local), local_iana_tz(), True
        except ValueError:
            return None, local_iana_tz(), True
    raw = part.get("dateTime")
    tz = str(part.get("timeZone") or local_iana_tz())
    if not raw:
        return None, tz, False
    try:
        dt = datetime.fromisoformat(str(raw).replace("Z", "+00:00"))
    except ValueError:
        return None, tz, False
    if dt.tzinfo is not None:
        return dt, tz, False
    if tz and tz != "UTC":
        try:
            return dt.replace(tzinfo=zoneinfo.ZoneInfo(tz)), tz, False
        except Exception:
            pass
    return dt.replace(tzinfo=timezone.utc), tz, False


def _parse_recurrence_lines(
    lines: list[str],
) -> tuple[str | None, tuple[datetime, ...], tuple[datetime, ...]]:
    """Split Google's `recurrence` array into (rrule, exdates, rdates).

    Google formats recurrence as iCal property strings:
      "RRULE:FREQ=WEEKLY;BYDAY=MO"
      "EXDATE;TZID=America/Los_Angeles:20260527T090000"
      "RDATE:20260601T090000Z"
    We need the RRULE value (without the prefix) for RecurrenceExpander, and
    EXDATE/RDATE values as datetime tuples.
    """
    import icalendar

    rrule_val: str | None = None
    exdates: list[datetime] = []
    rdates: list[datetime] = []
    for raw in lines or []:
        try:
            tag, rest = raw.split(":", 1) if ":" in raw else (raw, "")
        except Exception:
            continue
        name = tag.split(";", 1)[0].upper()
        if name == "RRULE" and rrule_val is None:
            rrule_val = rest
            continue
        if name in ("EXDATE", "RDATE"):
            try:
                # icalendar parses the full property; we only need its value list.
                cal = icalendar.Calendar.from_ical(
                    f"BEGIN:VCALENDAR\nBEGIN:VEVENT\nUID:x\nDTSTART:20260101T000000Z\n{raw}\nEND:VEVENT\nEND:VCALENDAR\n"
                )
                vevents = list(cal.walk("VEVENT"))
                if not vevents:
                    continue
                prop = vevents[0].get(name)
                if prop is None:
                    continue
                items = prop if isinstance(prop, list) else [prop]
                bucket = exdates if name == "EXDATE" else rdates
                for p in items:
                    dts = getattr(p, "dts", None) or []
                    for entry in dts:
                        val = getattr(entry, "dt", None)
                        if isinstance(val, datetime):
                            bucket.append(
                                val if val.tzinfo else val.replace(tzinfo=timezone.utc)
                            )
                        elif isinstance(val, _date_cls):
                            bucket.append(datetime.combine(val, time.min))
            except Exception:
                log.exception("Google: failed to parse recurrence line %r", raw)
    return rrule_val, tuple(exdates), tuple(rdates)


def _google_event_to_change(
    ev_json: dict[str, object], calendar_id: str
) -> EventChange | None:
    status = str(ev_json.get("status", ""))
    if status == "cancelled":
        return EventChange(
            kind="delete",
            uid=str(ev_json.get("iCalUID") or ev_json.get("id") or ""),
        )

    # Override (modified instance): store under the master's iCalUID so the
    # expander can find it as a sibling when rebuilding master instances.
    if ev_json.get("recurringEventId"):
        uid = str(ev_json.get("iCalUID") or ev_json.get("id") or "")
        dtstart, tz_start, all_day = _parse_google_dt(
            cast(dict[str, object] | None, ev_json.get("start"))
        )
        dtend, _, _ = _parse_google_dt(
            cast(dict[str, object] | None, ev_json.get("end"))
        )
        original_start_dt, _, _ = _parse_google_dt(
            cast(dict[str, object] | None, ev_json.get("originalStartTime"))
        )
        g_status = (
            "CONFIRMED"
            if status == "confirmed"
            else (status.upper() if status else "CONFIRMED")
        )
        transparency = (
            "TRANSPARENT" if ev_json.get("transparency") == "transparent" else "OPAQUE"
        )
        last_modified = None
        updated_raw = ev_json.get("updated")
        if isinstance(updated_raw, str):
            with contextlib.suppress(ValueError):
                last_modified = datetime.fromisoformat(
                    updated_raw.replace("Z", "+00:00")
                )
        override_event = Event(
            uid=uid,
            calendar_id=calendar_id,
            recurrence_id=original_start_dt,
            provider_event_id=cast(str | None, ev_json.get("id")),
            dtstart=dtstart,
            dtend=dtend,
            tz=tz_start,
            all_day=all_day,
            summary=str(ev_json.get("summary", "")),
            description=str(ev_json.get("description", "")),
            location=str(ev_json.get("location", "")),
            url=cast(str | None, ev_json.get("htmlLink")),
            rrule=None,
            status=g_status,
            transparency=transparency,
            last_modified=last_modified,
            etag=cast(str | None, ev_json.get("etag")),
            sequence=cast(int, ev_json.get("sequence", 0)),
        )
        return EventChange(kind="upsert", event=override_event, uid=uid)

    uid = str(ev_json.get("iCalUID") or ev_json.get("id") or "")

    dtstart, tz_start, all_day_start = _parse_google_dt(
        cast(dict[str, object] | None, ev_json.get("start"))
    )
    dtend, _tz_end, _all_day_end = _parse_google_dt(
        cast(dict[str, object] | None, ev_json.get("end"))
    )
    all_day = all_day_start

    rrule, exdates, rdates = _parse_recurrence_lines(
        cast(list[str], ev_json.get("recurrence") or [])
    )

    g_status = (
        "CONFIRMED"
        if status == "confirmed"
        else (status.upper() if status else "CONFIRMED")
    )
    transparency = (
        "TRANSPARENT" if ev_json.get("transparency") == "transparent" else "OPAQUE"
    )

    attendees_raw = cast(list[object], ev_json.get("attendees") or [])
    attendees: list[Attendee] = []
    self_response: str | None = None
    organizer_obj = cast(dict[str, object] | None, ev_json.get("organizer"))
    organizer: Organizer | None = None
    if isinstance(organizer_obj, dict) and organizer_obj.get("email"):
        organizer = Organizer(
            email=str(organizer_obj["email"]),
            display_name=str(organizer_obj["displayName"]) if organizer_obj.get("displayName") else None,
            is_self=bool(organizer_obj.get("self")),
        )
    for a in attendees_raw:
        if not isinstance(a, dict):
            continue
        email = str(a["email"]) if a.get("email") else ""
        if not email:
            continue
        is_self = bool(a.get("self"))
        is_org = bool(a.get("organizer"))
        resp_raw = str(a.get("responseStatus") or "").lower()
        response = _GOOGLE_RESPONSE_MAP.get(resp_raw, "NEEDS-ACTION")
        if is_self:
            self_response = _GOOGLE_RESPONSE_MAP.get(resp_raw)
        attendees.append(
            Attendee(
                email=email,
                display_name=str(a["displayName"]) if a.get("displayName") else None,
                response=response,
                is_organizer=is_org,
                is_self=is_self,
            )
        )

    last_modified: datetime | None = None
    updated_raw = ev_json.get("updated")
    if isinstance(updated_raw, str):
        with contextlib.suppress(ValueError):
            last_modified = datetime.fromisoformat(updated_raw.replace("Z", "+00:00"))

    event = Event(
        uid=uid,
        calendar_id=calendar_id,
        provider_event_id=cast(str | None, ev_json.get("id")),
        dtstart=dtstart,
        dtend=dtend,
        tz=tz_start,
        all_day=all_day,
        summary=str(ev_json.get("summary", "")),
        description=str(ev_json.get("description", "")),
        location=str(ev_json.get("location", "")),
        url=cast(str | None, ev_json.get("htmlLink")),
        rrule=rrule,
        exdates=exdates,
        rdates=rdates,
        attendees=tuple(attendees),
        organizer=organizer,
        status=g_status,
        self_response=self_response,
        transparency=transparency,
        last_modified=last_modified,
        etag=cast(str | None, ev_json.get("etag")),
        sequence=cast(int, ev_json.get("sequence", 0)),
    )
    return EventChange(kind="upsert", event=event, uid=uid)


GOOGLE_REDIRECT_URI = "http://127.0.0.1/lilical-google-callback"


def begin_google_auth() -> tuple[Any, str, str]:
    """Build (flow, auth_url, state) for an interactive auth-code sign-in.

    Returns (flow, auth_url, state). Pass auth_url to an embedded browser; on
    redirect to GOOGLE_REDIRECT_URI pass the captured URL and state to
    complete_google_auth.
    """
    from google_auth_oauthlib.flow import Flow  # type: ignore[reportMissingTypeStubs]

    _validate_client_config()
    flow = Flow.from_client_config(CLIENT_CONFIG, SCOPES, redirect_uri=GOOGLE_REDIRECT_URI)
    auth_url, state = flow.authorization_url(
        access_type="offline", prompt="select_account", include_granted_scopes="true"
    )
    return flow, auth_url, state


def complete_google_auth(flow: Any, captured_url: str, expected_state: str) -> str:
    """Exchange the captured redirect URL for credentials; return creds JSON."""
    import urllib.parse as _up

    qs = _up.parse_qs(_up.urlparse(captured_url).query)
    err = ((qs.get("error_description") or qs.get("error")) or [None])[0]
    if err:
        raise RuntimeError(f"Google returned an error: {err}")
    returned_state = (qs.get("state") or [None])[0]
    if returned_state is not None and returned_state != expected_state:
        raise RuntimeError("OAuth state mismatch — please try again.")
    flow.fetch_token(authorization_response=captured_url)
    return flow.credentials.to_json()


def _validate_client_config() -> None:
    installed = cast(dict[str, object], CLIENT_CONFIG.get("installed", {}))
    cid = str(installed.get("client_id", ""))
    if not cid or cid == "lilical-oauth":
        raise RuntimeError(
            "Google OAuth client credentials are not configured.\n\n"
            "Lilical looks for credentials in this order:\n"
            "  1. LILICAL_GOOGLE_CLIENT_ID + LILICAL_GOOGLE_CLIENT_SECRET env vars\n"
            "  2. Embedded build-time module (present in Flatpak/AppImage releases)\n"
            "  3. oauth_credentials.json at the repository root (dev mode)\n\n"
            "For local development, copy oauth_credentials.json.example to\n"
            "oauth_credentials.json and fill in your Google OAuth 2.0 client\n"
            "credentials (Desktop app type)."
        )


class GoogleBackend:
    def __init__(
        self,
        account_id: str,
        token_json: str | None = None,
        on_token_refreshed=None,
        identity: str = "",
    ) -> None:
        self.account_id = account_id
        self._token_json = token_json
        self._on_token_refreshed = on_token_refreshed
        self._identity = identity
        self._creds: Credentials | None = None
        self._http: Any = None  # httpx.AsyncClient, created lazily

    def _get_credentials(self) -> Credentials | None:
        if self._creds is not None:
            return self._creds
        if self._token_json:
            self._creds = Credentials.from_authorized_user_info(
                json.loads(self._token_json), SCOPES
            )
        else:
            self._creds = None
        return self._creds

    def get_token_json(self) -> str | None:
        return self._token_json

    def _acquire_token(self) -> str:
        creds = self._get_credentials()
        if creds is None:
            raise AuthExpired("no cached google credentials")
        if creds.valid:
            return str(creds.token)
        if creds.expired and creds.refresh_token:
            try:
                creds.refresh(Request())
            except Exception as exc:
                raise AuthExpired(f"google token refresh failed: {exc}") from exc
            self._token_json = creds.to_json()
            if self._on_token_refreshed is not None:
                try:
                    self._on_token_refreshed(self._token_json)
                except Exception:
                    log.exception("on_token_refreshed callback raised")
            return str(creds.token)
        raise AuthExpired("google credentials expired and no refresh token")

    def _get_http(self):
        if self._http is None:
            import httpx

            self._http = httpx.AsyncClient(timeout=30.0)
        return self._http

    async def _request(
        self,
        method: str,
        url: str,
        *,
        params: dict[str, str] | None = None,
        json_body: dict[str, Any] | None = None,
        headers: dict[str, str] | None = None,
    ):
        import httpx

        # Avoid thread-hop when credentials are still valid (the common case).
        if self._creds is not None and self._creds.valid:
            token: str = str(self._creds.token)
        else:
            token = await asyncio.to_thread(self._acquire_token)
        hdrs = {"Authorization": f"Bearer {token}", "Accept": "application/json"}
        if headers:
            hdrs.update(headers)
        full = url if url.startswith("http") else f"{GOOGLE_BASE}{url}"
        client = self._get_http()
        try:
            resp = await client.request(
                method, full, params=params, json=json_body, headers=hdrs
            )
        except httpx.HTTPError as exc:
            raise TransientError(str(exc)) from exc
        if resp.status_code >= 400:
            body_snippet = ""
            with contextlib.suppress(Exception):
                body_snippet = resp.text[:500]
            try:
                resp.raise_for_status()
            except httpx.HTTPStatusError as exc:
                if body_snippet:
                    exc.args = (
                        f"{exc.args[0] if exc.args else ''} body={body_snippet}",
                    )
                raise
        return resp

    async def aclose(self) -> None:
        if self._http is not None:
            await self._http.aclose()
            self._http = None

    async def _drain_list(
        self, calendar_id: str, initial_params: dict[str, str]
    ) -> AsyncIterator[tuple[list[EventChange], GoogleCursor]]:
        encoded = urllib.parse.quote(calendar_id, safe="")
        url = f"/calendars/{encoded}/events"
        params: dict[str, str] = dict(initial_params)
        while True:
            resp = await self._request("GET", url, params=params)
            data = resp.json()
            batch = [
                c
                for c in (
                    _google_event_to_change(ev, calendar_id)
                    for ev in data.get("items", [])
                )
                if c is not None
            ]
            next_page = data.get("nextPageToken")
            sync_token = None if next_page else data.get("nextSyncToken")
            yield batch, GoogleCursor(sync_token=sync_token)
            if not next_page:
                return
            params = {"pageToken": next_page}

    @_classify_errors
    async def list_calendars(self) -> list[dict[str, object]]:
        resp = await self._request(
            "GET",
            "/users/me/calendarList",
            params={"fields": "items(id,summary,backgroundColor)"},
        )
        data = resp.json()
        out = []
        for cal in data.get("items", []):
            colour = cal.get("backgroundColor")
            if colour and not colour.startswith("#"):
                colour = "#" + colour
            out.append(
                {
                    "id": cal["id"],
                    "display_name": cal.get("summary", cal["id"]),
                    "provider_id": cal["id"],
                    "color": (colour or "").lower() or None,
                }
            )
        return out

    @_classify_errors
    async def initial_sync(
        self, calendar_id: str
    ) -> AsyncIterator[tuple[list[EventChange], SyncCursor]]:
        async for batch, cursor in self._drain_list(
            calendar_id,
            {
                "singleEvents": "false",
                "showDeleted": "true",
                "maxResults": "2500",
                "fields": _EVENTS_LIST_FIELDS,
            },
        ):
            yield batch, cursor

    @_classify_errors
    async def incremental_sync(
        self, calendar_id: str, cursor: SyncCursor
    ) -> tuple[list[EventChange], SyncCursor]:
        if not isinstance(cursor, GoogleCursor) or not cursor.sync_token:
            raise CursorExpired(calendar_id)
        changes: list[EventChange] = []
        new_cursor: GoogleCursor = GoogleCursor(sync_token=cursor.sync_token)
        async for batch, c in self._drain_list(
            calendar_id,
            {
                "syncToken": cursor.sync_token,
                "singleEvents": "false",
                "showDeleted": "true",
                "maxResults": "2500",
                "fields": _EVENTS_LIST_FIELDS,
            },
        ):
            changes.extend(batch)
            new_cursor = c
        return changes, new_cursor

    @_classify_errors
    async def create_event(self, calendar_id: str, event: Event) -> Event:
        import dataclasses as _dc

        from lilical.backends._google_serializer import event_to_google_body

        encoded = urllib.parse.quote(calendar_id, safe="")
        body = event_to_google_body(event)
        resp = await self._request(
            "POST",
            f"/calendars/{encoded}/events",
            params={"sendUpdates": "none"},
            json_body=body,
        )
        data = resp.json()
        return _dc.replace(
            event,
            uid=data.get("iCalUID") or data["id"],
            provider_event_id=data["id"],
            etag=data.get("etag"),
            sequence=int(data.get("sequence", 0)),
        )

    @_classify_errors
    async def update_event(
        self, calendar_id: str, event: Event, if_match: str | None
    ) -> Event:
        import dataclasses as _dc

        from lilical.backends._google_serializer import event_to_google_body

        encoded_cal = urllib.parse.quote(calendar_id, safe="")
        pid = event.provider_event_id or event.uid
        encoded_ev = urllib.parse.quote(pid, safe="")
        body = event_to_google_body(event)
        extra_headers: dict[str, str] = {}
        if if_match:
            extra_headers["If-Match"] = if_match
        resp = await self._request(
            "PUT",
            f"/calendars/{encoded_cal}/events/{encoded_ev}",
            params={"sendUpdates": "none"},
            json_body=body,
            headers=extra_headers or None,
        )
        data = resp.json()
        return _dc.replace(
            event,
            uid=data.get("iCalUID") or data["id"],
            provider_event_id=data["id"],
            etag=data.get("etag"),
            sequence=int(data.get("sequence", 0)),
        )

    @_classify_errors
    async def delete_event(
        self, calendar_id: str, provider_event_id: str, if_match: str | None
    ) -> None:
        encoded_cal = urllib.parse.quote(calendar_id, safe="")
        encoded_ev = urllib.parse.quote(provider_event_id, safe="")
        await self._request(
            "DELETE",
            f"/calendars/{encoded_cal}/events/{encoded_ev}",
            params={"sendUpdates": "none"},
        )

    @_classify_errors
    async def update_instance(
        self,
        calendar_id: str,
        master_provider_id: str,
        recurrence_id_dt: datetime,
        event: Event,
    ) -> None:
        from lilical.backends._google_serializer import event_to_google_body

        rid_utc = recurrence_id_dt.astimezone(timezone.utc)
        original_start = rid_utc.strftime("%Y-%m-%dT%H:%M:%SZ")

        encoded_cal = urllib.parse.quote(calendar_id, safe="")
        encoded_master = urllib.parse.quote(master_provider_id, safe="")
        instances_resp = await self._request(
            "GET",
            f"/calendars/{encoded_cal}/events/{encoded_master}/instances",
            params={"originalStart": original_start},
        )
        items = instances_resp.json().get("items", [])
        if not items:
            raise PermanentError(
                f"Could not find Google occurrence for {recurrence_id_dt.isoformat()}"
            )
        instance_id: str = items[0]["id"]

        body = event_to_google_body(event)
        encoded_inst = urllib.parse.quote(instance_id, safe="")
        await self._request(
            "PATCH",
            f"/calendars/{encoded_cal}/events/{encoded_inst}",
            params={"sendUpdates": "none"},
            json_body=body,
        )

    @_classify_errors
    async def respond_to_event(
        self, calendar_id: str, event: Event, response: str
    ) -> Event | None:
        import dataclasses as _dc

        _to_google = {"ACCEPTED": "accepted", "TENTATIVE": "tentative", "DECLINED": "declined"}
        g_status = _to_google.get(response.upper())
        if not g_status or not event.provider_event_id:
            return None
        encoded_cal = urllib.parse.quote(calendar_id, safe="")
        encoded_ev = urllib.parse.quote(event.provider_event_id, safe="")
        # GET the current event to find the self attendee's email and full object.
        # GET the current attendees list so we can patch only the self entry.
        get_resp = await self._request(
            "GET",
            f"/calendars/{encoded_cal}/events/{encoded_ev}",
            params={"fields": "attendees"},
        )
        attendees_raw: list[dict[str, object]] = get_resp.json().get("attendees") or []
        found_self = any(isinstance(a, dict) and a.get("self") is True for a in attendees_raw)
        if not found_self:
            return None
        patched_attendees = [
            dict(a, responseStatus=g_status) if (isinstance(a, dict) and a.get("self") is True) else a
            for a in attendees_raw
        ]
        resp = await self._request(
            "PATCH",
            f"/calendars/{encoded_cal}/events/{encoded_ev}",
            params={"sendUpdates": "all"},
            json_body={"attendees": patched_attendees},
        )
        data = resp.json()
        return _dc.replace(
            event,
            uid=data.get("iCalUID") or data.get("id") or event.uid,
            provider_event_id=data.get("id") or event.provider_event_id,
            etag=data.get("etag") or event.etag,
            sequence=int(data.get("sequence", event.sequence or 0)),
            self_response=response,
        )

    @_classify_errors
    async def delete_instance(
        self,
        calendar_id: str,
        master_provider_id: str,
        recurrence_id_dt: datetime,
    ) -> None:
        rid_utc = recurrence_id_dt.astimezone(timezone.utc)
        original_start = rid_utc.strftime("%Y-%m-%dT%H:%M:%SZ")

        encoded_cal = urllib.parse.quote(calendar_id, safe="")
        encoded_master = urllib.parse.quote(master_provider_id, safe="")
        instances_resp = await self._request(
            "GET",
            f"/calendars/{encoded_cal}/events/{encoded_master}/instances",
            params={"originalStart": original_start},
        )
        items = instances_resp.json().get("items", [])
        if not items:
            raise PermanentError(
                f"Could not find Google occurrence for {recurrence_id_dt.isoformat()}"
            )
        instance_id: str = items[0]["id"]

        encoded_inst = urllib.parse.quote(instance_id, safe="")
        await self._request(
            "DELETE",
            f"/calendars/{encoded_cal}/events/{encoded_inst}",
            params={"sendUpdates": "none"},
        )

    def supported_contact_sources(self) -> tuple[str, ...]:
        return ("personal",)

    @_classify_errors
    async def list_contacts(
        self, source: str, cursor: dict | None
    ) -> tuple[list[Contact], dict | None, bool]:
        if source != "personal":
            return [], None, True
        try:
            return await self._list_carddav_contacts()
        except Exception as exc:
            log.warning("Google CardDAV contact listing failed: %s — falling back to empty", exc)
            return [], None, True

    async def _list_carddav_contacts(self) -> tuple[list[Contact], dict | None, bool]:
        import xml.etree.ElementTree as ET

        try:
            import vobject  # type: ignore[reportMissingModuleSource]
        except ImportError:
            log.warning("vobject not installed — Google CardDAV contact parsing skipped")
            return [], None, True

        identity = urllib.parse.quote(self._identity, safe="@")
        ab_url = f"https://www.googleapis.com/carddav/v1/principals/{identity}/lists/default/"
        body = (
            "<?xml version='1.0' encoding='utf-8'?>"
            "<C:addressbook-query xmlns:D='DAV:' xmlns:C='urn:ietf:params:xml:ns:carddav'>"
            "<D:prop><D:getetag/><C:address-data/></D:prop>"
            "</C:addressbook-query>"
        )

        token = await asyncio.to_thread(self._acquire_token)
        client = self._get_http()
        resp = await client.request(
            "REPORT",
            ab_url,
            content=body.encode(),
            headers={
                "Authorization": f"Bearer {token}",
                "Depth": "1",
                "Content-Type": "application/xml",
            },
        )
        if resp.status_code >= 400:
            log.warning("Google CardDAV REPORT returned HTTP %d", resp.status_code)
            return [], None, True

        root = ET.fromstring(resp.content)
        contacts: list[Contact] = []
        for ad in root.iter("{urn:ietf:params:xml:ns:carddav}address-data"):
            if not ad.text:
                continue
            try:
                vcard = vobject.readOne(ad.text)
                name: str | None = None
                fn = getattr(vcard, "fn", None)
                if fn is not None:
                    name = str(fn.value).strip() or None
                emails_prop = getattr(vcard, "email_list", None) or []
                if not emails_prop:
                    ep = getattr(vcard, "email", None)
                    emails_prop = [ep] if ep else []
                for ep in emails_prop:
                    addr = str(ep.value).strip().lower()
                    if addr and "@" in addr:
                        contacts.append(Contact(
                            email=addr,
                            display_name=name,
                            source="personal",
                            account_id=self.account_id,
                        ))
            except Exception as exc:
                log.debug("Google CardDAV vcard parse error: %s", exc)

        return contacts, None, True
