"""Generate src/lilical/_oauth_embedded.py from oauth_credentials.json.

Called by both the Flatpak and AppImage build systems before bundling so that
client credentials are frozen into the distributed artifact without being
committed to the repository.

Usage:
    python tools/generate_oauth_embedded.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

repo_root = Path(__file__).resolve().parent.parent
json_path = repo_root / "oauth_credentials.json"
out_path = repo_root / "src" / "lilical" / "_oauth_embedded.py"

if not json_path.is_file():
    print(
        f"error: {json_path} not found.\n"
        "Copy oauth_credentials.json.example to oauth_credentials.json "
        "and fill in your Google OAuth client credentials.",
        file=sys.stderr,
    )
    sys.exit(1)

with json_path.open() as f:
    data = json.load(f)

try:
    installed = data["installed"]
    client_id = str(installed["client_id"])
    client_secret = str(installed["client_secret"])
    auth_uri = str(
        installed.get("auth_uri", "https://accounts.google.com/o/oauth2/auth")
    )
    token_uri = str(
        installed.get("token_uri", "https://oauth2.googleapis.com/token")
    )
except (KeyError, TypeError) as exc:
    print(f"error: malformed oauth_credentials.json: {exc}", file=sys.stderr)
    sys.exit(1)

out_path.write_text(
    "# AUTO-GENERATED by tools/generate_oauth_embedded.py\n"
    "# Do not edit or commit — regenerated on each build.\n"
    f"CLIENT_ID = {client_id!r}\n"
    f"CLIENT_SECRET = {client_secret!r}\n"
    f"AUTH_URI = {auth_uri!r}\n"
    f"TOKEN_URI = {token_uri!r}\n"
)
print(f"wrote {out_path.relative_to(repo_root)}")
